package overleafmcp

const (
	ToolAuthStatus          = "overleaf_auth_status"
	ToolAuthLogin           = "overleaf_auth_login"
	ToolAuthLogout          = "overleaf_auth_logout"
	ToolListProjects         = "overleaf_list_projects"
	ToolListTags             = "overleaf_list_tags"
	ToolCreateTag            = "overleaf_create_tag"
	ToolEditTag              = "overleaf_edit_tag"
	ToolDeleteTag            = "overleaf_delete_tag"
	ToolAssignProjectTags    = "overleaf_assign_project_tags"
	ToolRemoveProjectTags    = "overleaf_remove_project_tags"
	ToolListFiles            = "overleaf_list_files"
	ToolReadFile             = "overleaf_read_file"
	ToolCreateProject        = "overleaf_create_project"
	ToolCreateFile           = "overleaf_create_file"
	ToolUpdateFile           = "overleaf_update_file"
	ToolDeleteFile           = "overleaf_delete_file"
	ToolUploadFiles          = "overleaf_upload_files"
	ToolUploadProjectArchive = "overleaf_upload_project_archive"
	ToolCompileProject       = "overleaf_compile_project"
	ToolDownloadPDF          = "overleaf_download_pdf"
	ToolSyncPull             = "overleaf_sync_pull"
	ToolSyncPush             = "overleaf_sync_push"
)
